apiVersion:     apps/v1
kind: Deployment
metadata:
        name: elasticsearch
spec:
        selector:
                matchLabels:
                        app: elasticsearch
        replicas: 1
        template:
                metadata:
                        labels:
                                app: elasticsearch
                spec:
                        containers:
                        - name: elasticsearch
                          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
                          env:
                          - name: discovery.type
                            value: single-node
                          ports:
                          - containerPort: 9200
